module.exports = [
  { name: 'vue', library: 'Vue', js: 'https://cdn.gd.838383.xyz/js_new/vue.min.js', css: '' },
  { name: 'vue-i18n', library: 'VueI18n', js: 'https://cdn.gd.838383.xyz/js_new/vue-i18n.min.js', css: '' },
  { name: 'vue-router', library: 'VueRouter', js: 'https://cdn.gd.838383.xyz/js_new/vue-router.min.js', css: '' },
  { name: 'vuex', library: 'Vuex', js: 'https://cdn.gd.838383.xyz/js_new/vuex.js', css: '' },
  { name: 'axios', library: 'axios', js: 'hhttps://cdn.gd.838383.xyz/js_new/axios.min.js', css: '' },
  { name: 'element-ui', library: 'ELEMENT', js: 'https://cdn.gd.838383.xyz/js_new/index.js'/* , css: 'https://cdn.gd.838383.xyz/js_new/index.css' */ },
  { name: 'lodash', library: '_', js: 'https://cdn.gd.838383.xyz/js_new/lodash.min.js', css: '' },
  { name: 'js-cookie', library: 'Cookies', js: 'https://cdn.gd.838383.xyz/js_new/js.cookie.min.js', css: '' },
  { name: 'lowdb', library: 'low', js: 'https://cdn.gd.838383.xyz/js_new/low.min.js', css: '' },
  { name: 'lowdb/adapters/LocalStorage', library: 'LocalStorage', js: 'https://cdn.gd.838383.xyz/js_new/LocalStorage.min.js', css: '' },
  { name: '', library: '', js: 'https://cdn.gd.838383.xyz/js_new/font_1760192_8add3xcxs4u.js', css: '' },
  { name: '', library: '', js: '', css: 'https://cdn.gd.838383.xyz/js_new/font-awesome.min.css' },
  { name: '', library: '', js: '', css: 'https://cdn.gd.838383.xyz/js_new/font-awesome-animation.min.css' },
]